cat/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'cat'

urlpatterns = [
    path('', views.index, name='index'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 관리자 페이지에 접속하는 url
    path('admin/', admin.site.urls),
    # 주소 뒤에 아무것도 입력하지 않았을 때 접속하는 페이지 = ner/news_list.html
    path('', include('ner.urls')),
    # 카테고라이저 페이지에 접속하는 url
    path('cat', include('cat.urls')),
    # 팀 소개 페이지에 접속하는 url
    path('team/', include('team.urls')),
]

ner/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'ner'

urlpatterns = [
    # 주소 뒤에 아무것도 입력하지 않았을 때 접속하는 페이지 = ner/news_list.html
    path('', views.index, name='index'),
    # 뉴스를 클릭했을 때 접속하는 페이지 = ner/news_detail.html
    path('<int:news_id>/', views.detail, name='detail'),
]

ner/models.py
from django.db import models


# Create your models here.
# 데이터베이스 저장 형식 (관리자)
class NewsData(models.Model):
    subject = models.CharField(max_length=200)
    category = models.CharField(max_length=25)
    create_date = models.DateTimeField()
    author = models.CharField(max_length=40, default='')
    content = models.TextField()
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.subject

ner/views.py
from django.shortcuts import render, get_object_or_404
from .models import NewsData
from django.core.paginator import Paginator
from django.db.models import Q
import requests
import json

# 기능 : NER 메인 페이지(ner/news_list.html) 호출
# 최종 업데이트: 2021/12/30
# 최종 작업자: 최우진
# input
# request : 서버 요청
# page : int
# kw : str
# so : str
# output
# render(request, 'ner/news_list.html', context) : request가 있을 경우 context를 활용해 ner/news_list.html 파일 렌더링
# context : {'news_list' : paginator object, 'page': int, 'kw': str}
def index(request):
    # 페이징
    page = request.GET.get('page', '1')
    # 검색어
    kw = request.GET.get('kw', '')
    # 최신순 정렬
    so = request.GET.get('so', 'recent')
    # 뉴스 목록 조회
    news_list = NewsData.objects.order_by('-create_date')
    # 검색어가 있을 경우
    if kw:
        news_list = news_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(category__icontains=kw)
        ).distinct()
        # 최신순 정렬을 선택한 경우 그대로 출력
        if so == 'recent':
            pass
        # 관련순 정렬을 선택한 경우
        else:
            sort_list = []
            # 뉴스 리스트 전체에서 제목과 본문 중 키워드를 카운트
            for news in news_list:
                sort_list.append((news.subject.count(kw) + news.content.count(kw), news))
            # 키워드를 많이 포함한 순서로 정렬
            news_list = sorted(sort_list, key=lambda x:x[0], reverse=True)
            news_list = [i[1] for i in news_list]
    # 페이징 처리
    paginator = Paginator(news_list, 20)
    page_obj = paginator.get_page(page)
    context = {'news_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'ner/news_list.html', context)

# 기능 : NER 적용 결과 페이지(ner/news_detail.html) 호출
# 최종 업데이트: 2021/12/30
# 최종 작업자: 최우진
# input
# request: 서버 요청
# news_id : int (뉴스의 id값)
# output
# render(request, 'ner/news_list.html', context) : request가 있을 경우 context를 활용해 ner/news_detail.html 파일 렌더링
# context : {'news': str(DB object)}
def detail(request, news_id):
    # 뉴스 내용 출력
    news = get_object_or_404(NewsData, pk=news_id)
    # iframe_colored = apply_ner(news.content)
    iframe = open('.\static\iframe.html', 'w', encoding='utf8')
    # iframe.write('<p style="color: #f8f9fa; line-height: 1.8;">' + f'{iframe_colored}' + '</p>')
    iframe.close()
    context = {'news': news}
    return render(request, 'ner/news_detail.html', context)

# 기능 : 텍스트에 span 태크를 입혀 반환함(색 입히기 위해)
# 최종 업데이트: 2021/12/31
# 최종 작업자: 조강희
# input
# content : str(html 태그 없는 텍스트)
# output
# final : str(html 태그 붙은 텍스트)
def apply_ner(content):
    # 결과물에 따른 색상 딕셔너리
    colors = {'동물':'#6b60aa;','용어': '#3182bd;','문명':'#3182bd;', '사건':'#cc2673;', '인물':'#ffd400', '기관':'#e6550d;', '지역':'#fdae6b;', '날짜':'#31a354;','시간':'#31a354;', '인공물':'#addd8e;', '수량':'#c994c7;', '물질':'#addd8e;'}
    
    # 문장 나누기
    # split = kss.split_sentences(content)
    split = content.split('. ')
    
    # 최종 결과물이 들어갈 변수
    final = ''
    
    # 문장별로 반복문 돌려 결과물에 색상 적용
    for sentence in split:
        # ner 포맷으로 변경
        sentence_dict = {'texts':[sentence]}
        
        # request and responce
        req = requests.post("http://192.168.0.221:3333/ner", json=sentence_dict)
        res = json.loads(req.text)
        
        # 인덱스 순으로 정렬
        res = sorted(res[0],key=lambda x:x[0])
        
        # 텍스트 삽입과 html 태그 계산을 위한 임시 변수
        cnt_temp = 0
        sentence_temp = list(sentence)
        
        # 답변별로 반복문 돌려 정답 찾기
        for result in res:
            tag_start = f'<span style="color:{colors[result[2]]}">' # 색상 적용
            tag_end = '</span>'
            if result[1] == sentence[result[0]:result[0]+len(result[1])]:
                sentence_temp.insert(result[0]+cnt_temp, tag_start)
                cnt_temp+=1
                sentence_temp.insert(result[0]+len(result[1])+cnt_temp, tag_end)
                cnt_temp+=1
            else:
                continue
        final += ''.join(sentence_temp)
        final += '. '
    
    return final

templates/ner/news_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container my-5">
    <!-- news_information -->
    <div class="card bg-dark col-12 p-4 text-light my-4">
        <div class="card_body row align-items-center">
            <div class="card-text col-8" style="line-height: 1.8;">{{ news.subject }}</div>
            <div class="card-text col-4 text-right" style="line-height: 1.8;">{{ news.category }}, {{ news.author }}<br>{{ news.create_date }}</div>
        </div>
    </div>
    <!-- /news_information -->
    <div class="card bg-dark col-12 p-4">
        <div class="card_body row  align-items-center">
            <!-- news_contents, legend -->
            <iframe class="col-10 pl-4 my-3" width="90%" height="520px" style="border: none;" src="{% static 'iframe.html' %}">본문 NER 결과</iframe>
            <div class="col-2 text-center font-weight-bold">
                <span style="color: #fdae6b;">지역</span><br><br>
                <span style="color: #e6550d;">기관</span><br><br>
                <span style="color: #ffd400;">인물</span><br><br>
                <span style="color: #3182bd;">용어 / 문명</span><br><br>
                <span style="color: #cc2673;">사건</span><br><br>
                <span style="color: #31a354;">날짜 / 시간</span><br><br>
                <span style="color: #c994c7;">수량</span><br><br>
                <span style="color: #addd8e;">인공물 / 물질</span><br><br>
                <span style="color: #6b60aa;">동물</span>
            </div>
            <!-- /news_contents, legend -->
        </div>
        <div class="row col-12 justify-content-center">
            <!-- back_button -->
            <button type=button value="Previous Page" onClick="window.history.back();return false;" class="btn btn-dark col-2 mx-3 p-2 text-light">목록으로</button>
            <!-- /back_button -->
        </div>
    </div>
</div>
{% endblock %}

templates/ner/news_list.html
{% extends 'base.html' %}
{% load ner_filter %}
{% block content %}
<div class="container my-5">
    <h1 class="text-center text-dark">Named Entity Recognition</h1><br>
    <div class="col-12 mb-3">
        <caption class="col-12 display-block text-dark" style="caption-side: top;">
            ▶ ㈜TwoBlockAI에서 제공한 학습용 NER(개체명 인식)모델을 활용했습니다.<br>
            ▶ Naver에서 '21년 10월 6일부터 25일까지 20일치 약 18,000건의 기사를 수집하여 정제한 데이터입니다.<br>
            ▶ 해당 게시글 클릭시 기사 본문의 개체명 별 색상이 표시됩니다.(※ 게시글 내 색상표 참고)<br>
        </caption>
    </div>
    <!-- search_function -->
    <div class="row justify-content-between mb-5">
        <div class="col-3">
            <select class="form-control so">
                <option value="relation">관련순 (키워드 빈도순)</option>
                <option value="recent">최신순 (작성일자 기준)</option>
            </select>
        </div>
        <div class="col-8 input-group">
            <input type="text" class="form-control border-dark rounded kw" placeholder="검색어를 입력하세요." value="{{ kw|default_if_none:'' }}">
            <button class="btn btn-block btn-outline-dark my-2" type="button" id="btn_search">검색</button>
        </div>
    </div>
    <!-- /search_function -->
    <!-- news_table -->
    <table class="table table-hover">
        <thead>
        <tr class="text-center thead-dark">
            <th class="font-weight-normal">번호</th>
            <th style="width:60%;" class="font-weight-normal">제목</th>
            <th class="font-weight-normal">작성일자</th>
            <th class="font-weight-normal">언론사</th>
        </tr>
        </thead>
        <tbody class="table-sm">
        {% if news_list %}
        {% for news in news_list %}
        <tr class="text-center" onClick="location.href='{% url 'ner:detail' news.id %}'">
            <td>{{ news_list.paginator.count|sub:news_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td style="text-align:left;">{{ news.subject }}</td>
            <td>{{ news.create_date }}</td>
            <td>{{ news.author }}</td>
        </tr>
        
        </a>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">No Data.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- /news_table -->
    <!-- pages -->
    <ul class="pagination justify-content-center">
        <!-- previous -->
        {% if news_list.has_previous %}
        <li class="page-item">
            <a class="page-link text-dark" data-page="{{ news_list.previous_page_number }}" href="#">Prev</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">Prev</a>
        </li>
        {% endif %}
        <!-- /previous -->
        <!-- page-list -->
        {% for page_number in news_list.paginator.page_range %}
        {% if page_number >= news_list.number|add:-5 and page_number <= news_list.number|add:5 %}
            {% if page_number == news_list.number %}
            <li class="page-item" aria-current="page"><a class="page-link text-dark bg-secondary" data-page="{{ page_number }}" href="#">{{ page_number }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link text-dark" data-page="{{ page_number }}" href="#">{{ page_number }}</a></li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- /page-list -->
        <!-- next -->
        {% if news_list.has_next %}
        <li class="page-item">
            <a class="page-link text-dark" data-page="{{ news_list.next_page_number }}" href="#">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">Next</a>
        </li>
        {% endif %}
        <!-- /next -->
    </ul>
    <!-- /pages -->
</div>
<!-- form -->
<form id="searchForm" method="get" action="{% url 'ner:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
<!-- /form -->
{% endblock %}