cat/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'cat'

urlpatterns = [
    path('', views.index, name='index'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 관리자 페이지에 접속하는 url
    path('admin/', admin.site.urls),
    # 주소 뒤에 아무것도 입력하지 않았을 때 접속하는 페이지 = ner/news_list.html
    path('', include('ner.urls')),
    # 카테고라이저 페이지에 접속하는 url
    path('cat', include('cat.urls')),
    # 팀 소개 페이지에 접속하는 url
    path('team/', include('team.urls')),
]

ner/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'ner'

urlpatterns = [
    # 주소 뒤에 아무것도 입력하지 않았을 때 접속하는 페이지 = ner/news_list.html
    path('', views.index, name='index'),
    # 뉴스를 클릭했을 때 접속하는 페이지 = ner/news_detail.html
    path('<int:news_id>/', views.detail, name='detail'),
]

team/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'team'

urlpatterns = [
    path('', views.team, name='team'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- /meta -->
    <!-- link -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- /link -->
    <!-- title -->
    <title>project Queue!</title>
    <!-- /title -->
</head>
<body>
{% include "navbar.html" %}
<!-- content -->
{% block content %}
{% endblock %}
<!-- /content -->
<!-- javascript -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
<!-- /javascript -->
</body>
</html>

templates/navbar.html
{% load static %}
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
    <a class="navbar-logo" href="{% url 'team:team' %}"><img src="{% static 'logo\logo.png' %}" alt="Team_Queue_Logo" width="150px"></a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link text-light" href="{% url 'ner:index' %}">  Named Entity Recognition</a></li>
            <li class="nav-item"><a class="nav-link text-light" href="{% url 'cat:index' %}">  News Classifier</a></li>
        </ul>
    </div>
</nav>
<!-- /navbar -->